BASE_URL = "https://google.serper.dev"

KEYWORDS = [
    "latest",
    "today",
    "new",
    "recent",
    "current",
    "now",
    "this week",
    "this month",
    "this year",
    "updated",  
    "breaking",
    "news",
    "trending",
    "live",
    "real-time",
    "yesterday",
    "tomorrow",
    "upcoming",
    "fresh",
    "modern",
    "contemporary",
    "just released",
    "just announced",
    "just published",
    "what happened",
    "what's new",
    "what's happening",
    "price",
    "stock",
    "weather",
    "forecast",
    "latest news",
    "latest updates",
    "latest trends",
    "latest events",
    "latest developments",
    "latest information"
]